/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.tasktrack.view;

import com.tasktrack.model.TaskModel;
import com.tasktrack.util.ValidationUtil;
import java.awt.Color;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SUPRIYA
 */
public class TaskTrack extends javax.swing.JFrame {


    private java.awt.CardLayout cardLayout;
    private List<TaskModel> taskList;
    private final ValidationUtil validator;
    private final Color errorColor = new Color(255, 51, 0);
    private final Color correctColor = new Color(113, 202, 134);

    /**
     * Creates new fom NewJFrame
     */
    public TaskTrack() {
        initComponents();
        validator = new ValidationUtil();
        initializeLayout();
        initializeData();
        startProgress();
    }

    private void initializeLayout() {
        cardLayout = new java.awt.CardLayout();
        getContentPane().setLayout(cardLayout);

        // Add panels with unique identifiers
        getContentPane().add(pnlLoadingPage, "LoadingScreen");
        getContentPane().add(pnlLoginScreen, "LoginScreen");
        getContentPane().add(pnlMainScreen, "MainScreen");
        getContentPane().add(pnlTaskForm, "TaskScreen");

        // Start with the loading screen
        cardLayout.show(getContentPane(), "LoadingScreen");
    }

    private void initializeData() {
        taskList = new LinkedList<>();

        //Registering sample students
        registerTask(new TaskModel(56438, "Wireframe Design", "Prithivi Maharjan", "Ram", "2024-11-06", "2024-11-20", "80%", "Missed"));
        registerTask(new TaskModel(90063, "Database Report", "Aadesh Tandukar", "Shyam", "2024-11-21", "2024-12-31", "100%", "Completed"));
        registerTask(new TaskModel(86413, "Calculus Revision", "Indra Dhakal", "Hari", "2024-11-09", "2024-12-01", "65%", "In progress"));
        registerTask(new TaskModel(49201, "CRUD Operations", "Prithivi Maharjan", "Rita", "2024-12-09", "2025-01-25", "40%", "In progress"));
        registerTask(new TaskModel(20890, "UNF creation", "Aadesh Tandukar", "Sita", "2024-12-20", "2025-02-10", "30%", "In progress"));
    }

    private void startProgress() {
        javax.swing.SwingWorker<Void, Integer> worker = new javax.swing.SwingWorker<>() {
            @Override
            protected Void doInBackground() throws Exception {
                for (int i = 0; i <= 100; i++) {
                    Thread.sleep(30); // Simulated delay for progress bar
                    publish(i);
                }
                return null;
            }

            @Override
            protected void process(java.util.List<Integer> chunks) {
                int progress = chunks.get(chunks.size() - 1);
                pgBarLoadingScreen.setValue(progress);
            }

            @Override
            protected void done() {
                loadScreen("LoginScreen"); // Switch to login screen
            }
        };
        worker.execute();
    }

    // Method to add student data and populate the table
    private void registerTask(TaskModel task) {
        taskList.add(task);
        DefaultTableModel model = (DefaultTableModel) tblTasks.getModel();
        model.addRow(new Object[]{
            task.getTaskId(), task.getTaskTitle(), task.getAssignedBy(), task.getAssignedTo(),
            task.getAssignedDate(), task.getDueDate(), task.getProgress(), task.getStatus()});
    }

    private void loadScreen(String screenName) {
        cardLayout.show(getContentPane(), screenName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainScreen = new javax.swing.JPanel();
        lblMainBar = new javax.swing.JLabel();
        tabPaneMain = new javax.swing.JTabbedPane();
        pnlHome = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnGetStarted = new javax.swing.JButton();
        pnlTasks = new javax.swing.JPanel();
        pnlTaskListTitle = new javax.swing.JPanel();
        lblTaskListTitle = new javax.swing.JLabel();
        spTblTasks = new javax.swing.JScrollPane();
        tblTasks = new javax.swing.JTable();
        btnTaskDataForm = new javax.swing.JButton();
        pnlAboutUs = new javax.swing.JPanel();
        pnlAboutUsTitle = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlLogo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pnlLoginScreen = new javax.swing.JPanel();
        lblLoginPageSideScreenIcon = new javax.swing.JLabel();
        lblTaskTrack = new javax.swing.JLabel();
        lblWelcomeTo = new javax.swing.JLabel();
        pnlLoginWithFacebook = new javax.swing.JPanel();
        lblLoginWithFacebook = new javax.swing.JLabel();
        lblFacebookIcon = new javax.swing.JLabel();
        pnlLoginWithGoogle = new javax.swing.JPanel();
        lblLoginWithGoogle = new javax.swing.JLabel();
        lblGoogleIcon = new javax.swing.JLabel();
        lblOrLabel = new javax.swing.JLabel();
        txtFieldUsername = new javax.swing.JTextField();
        lblUsernameIcon = new javax.swing.JLabel();
        lblUsernameTitle = new javax.swing.JLabel();
        lblPasswordIcon = new javax.swing.JLabel();
        txtFieldPassword = new javax.swing.JTextField();
        lblPasswordTitle = new javax.swing.JLabel();
        lblForgotPassword = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        lblLoginError = new javax.swing.JLabel();
        pnlTaskForm = new javax.swing.JPanel();
        pnlTaskDataFormTitle = new javax.swing.JPanel();
        lblTaskDataFormTitle = new javax.swing.JLabel();
        txtFieldAssignedDate = new javax.swing.JTextField();
        txtFieldTaskId = new javax.swing.JTextField();
        txtFieldProgress = new javax.swing.JTextField();
        txtFieldTaskTitle = new javax.swing.JTextField();
        cbStatus = new javax.swing.JComboBox<>();
        txtFieldDueDate = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        txtFieldAssignedTo = new javax.swing.JTextField();
        txtFieldAssignedBy = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        lblErrorMsgTaskId = new javax.swing.JLabel();
        lblErrorMsgTaskTitle = new javax.swing.JLabel();
        lblErrorMsgAssignedDate = new javax.swing.JLabel();
        lblErrorMsgDueDate = new javax.swing.JLabel();
        lblErrorMsgProgress = new javax.swing.JLabel();
        lblErrorMsgAssignedBy = new javax.swing.JLabel();
        lblErrorMsgAssignedTo = new javax.swing.JLabel();
        pnlLoadingPage = new javax.swing.JPanel();
        lblLoadingPageLogo = new javax.swing.JLabel();
        pgBarLoadingScreen = new javax.swing.JProgressBar(0,100);
        lblLoading = new javax.swing.JLabel();

        pnlMainScreen.setBackground(new java.awt.Color(255, 255, 255));
        pnlMainScreen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlMainScreen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblMainBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tasktrack/resources/mainBar.png"))); // NOI18N
        lblMainBar.setText("jLabel1");

        tabPaneMain.setBackground(new java.awt.Color(255, 255, 255));
        tabPaneMain.setForeground(new java.awt.Color(184, 134, 125));
        tabPaneMain.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N

        pnlHome.setBackground(new java.awt.Color(230, 240, 230));

        jTextField1.setBackground(new java.awt.Color(230, 240, 230));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jTextField1.setText("Connect.Track.Conquer");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setBackground(new java.awt.Color(230, 240, 230));
        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField2.setText("Stay on top of your work with task track.");
        jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tasktrack/resources/logo.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        btnGetStarted.setBackground(new java.awt.Color(242, 224, 201));
        btnGetStarted.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGetStarted.setText("Get Started");
        btnGetStarted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetStartedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(242, 242, 242))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(279, 279, 279))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                .addContainerGap(265, Short.MAX_VALUE)
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(169, 169, 169))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                        .addComponent(btnGetStarted, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(337, 337, 337))))
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGetStarted, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        tabPaneMain.addTab("Home", pnlHome);
        pnlHome.getAccessibleContext().setAccessibleName("Home");

        pnlTasks.setBackground(new java.awt.Color(255, 255, 255));

        pnlTaskListTitle.setBackground(new java.awt.Color(221, 194, 173));
        pnlTaskListTitle.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));
        pnlTaskListTitle.setForeground(new java.awt.Color(51, 51, 51));

        lblTaskListTitle.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblTaskListTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTaskListTitle.setText("Task List");

        javax.swing.GroupLayout pnlTaskListTitleLayout = new javax.swing.GroupLayout(pnlTaskListTitle);
        pnlTaskListTitle.setLayout(pnlTaskListTitleLayout);
        pnlTaskListTitleLayout.setHorizontalGroup(
            pnlTaskListTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTaskListTitleLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTaskListTitle)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnlTaskListTitleLayout.setVerticalGroup(
            pnlTaskListTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTaskListTitleLayout.createSequentialGroup()
                .addComponent(lblTaskListTitle)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        spTblTasks.setBackground(new java.awt.Color(255, 255, 255));
        spTblTasks.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        spTblTasks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spTblTasksMouseClicked(evt);
            }
        });

        tblTasks.setBackground(new java.awt.Color(230, 240, 230));
        tblTasks.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        tblTasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Task ID", "Task Title", "Assigned By", "Assigned To", "Assigned Date", "Due Date", "Progress", "Status"
            }
        ));
        tblTasks.setGridColor(new java.awt.Color(0, 102, 102));
        tblTasks.setRowHeight(30);
        tblTasks.setSelectionBackground(new java.awt.Color(255, 204, 204));
        tblTasks.setSelectionForeground(new java.awt.Color(204, 0, 0));
        tblTasks.setShowGrid(true);
        tblTasks.setSurrendersFocusOnKeystroke(true);
        tblTasks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTasksMouseClicked(evt);
            }
        });
        spTblTasks.setViewportView(tblTasks);

        btnTaskDataForm.setBackground(new java.awt.Color(221, 194, 173));
        btnTaskDataForm.setText("Click to open task data form");
        btnTaskDataForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaskDataFormActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTasksLayout = new javax.swing.GroupLayout(pnlTasks);
        pnlTasks.setLayout(pnlTasksLayout);
        pnlTasksLayout.setHorizontalGroup(
            pnlTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTasksLayout.createSequentialGroup()
                .addGroup(pnlTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTasksLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(pnlTaskListTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(spTblTasks, javax.swing.GroupLayout.PREFERRED_SIZE, 913, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlTasksLayout.createSequentialGroup()
                        .addGap(364, 364, 364)
                        .addComponent(btnTaskDataForm, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTasksLayout.setVerticalGroup(
            pnlTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTasksLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(pnlTaskListTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(spTblTasks, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addGap(79, 79, 79)
                .addComponent(btnTaskDataForm)
                .addGap(64, 64, 64))
        );

        tabPaneMain.addTab("Tasks", pnlTasks);

        pnlAboutUs.setBackground(new java.awt.Color(230, 240, 230));

        pnlAboutUsTitle.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 120)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(184, 134, 125));
        jLabel2.setText("About ");

        jLabel1.setBackground(new java.awt.Color(184, 134, 125));
        jLabel1.setFont(new java.awt.Font("Cambria", 0, 120)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(184, 134, 125));
        jLabel1.setText("Us");

        javax.swing.GroupLayout pnlAboutUsTitleLayout = new javax.swing.GroupLayout(pnlAboutUsTitle);
        pnlAboutUsTitle.setLayout(pnlAboutUsTitleLayout);
        pnlAboutUsTitleLayout.setHorizontalGroup(
            pnlAboutUsTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAboutUsTitleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlAboutUsTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(0, 0, 0))
        );
        pnlAboutUsTitleLayout.setVerticalGroup(
            pnlAboutUsTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAboutUsTitleLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlLogo.setBackground(new java.awt.Color(213, 194, 177));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tasktrack/resources/logo.png"))); // NOI18N
        lblLogo.setText("jLabel1");

        javax.swing.GroupLayout pnlLogoLayout = new javax.swing.GroupLayout(pnlLogo);
        pnlLogo.setLayout(pnlLogoLayout);
        pnlLogoLayout.setHorizontalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogoLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        pnlLogoLayout.setVerticalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Microsoft Tai Le", 0, 24)); // NOI18N
        jLabel4.setText("Welcome to Task Track");

        jTextArea1.setBackground(new java.awt.Color(230, 240, 230));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Century", 3, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("      the ultimate solution for efficient task \n        management and seamless project \n                            tracking.\n\n     At, Task Track we beleive that every \n    successful project begins with effective\n    planning, clear goals and streamlined \n                     communication.\n\n      Empower you and your team with us.");
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel5.setBackground(new java.awt.Color(232, 204, 187));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Contact Task Track Team at:");

        jLabel6.setText("                      tasktrack2004@gmail.com");

        jLabel7.setText("Message");

        jLabel8.setText("------------------------------------------------------");

        jLabel9.setText("Email:");

        jLabel10.setText("------------------------------------------------------");

        jLabel11.setText("Full Name:");

        jLabel12.setText("------------------------------------------------------");

        jButton1.setBackground(new java.awt.Color(222, 239, 218));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Contact Us");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAboutUsLayout = new javax.swing.GroupLayout(pnlAboutUs);
        pnlAboutUs.setLayout(pnlAboutUsLayout);
        pnlAboutUsLayout.setHorizontalGroup(
            pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAboutUsLayout.createSequentialGroup()
                .addGroup(pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAboutUsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlAboutUsLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel5))
                    .addGroup(pnlAboutUsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11))
                    .addGroup(pnlAboutUsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8))
                    .addGroup(pnlAboutUsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9))
                    .addGroup(pnlAboutUsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10))
                    .addGroup(pnlAboutUsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(pnlAboutUsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12))
                    .addGroup(pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAboutUsLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlAboutUsLayout.createSequentialGroup()
                            .addGap(66, 66, 66)
                            .addComponent(jButton1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1)
                    .addComponent(pnlLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(266, Short.MAX_VALUE))
        );
        pnlAboutUsLayout.setVerticalGroup(
            pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAboutUsLayout.createSequentialGroup()
                .addGroup(pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlAboutUsLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1))
                    .addComponent(pnlAboutUsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAboutUsLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        tabPaneMain.addTab("About Us", pnlAboutUs);

        javax.swing.GroupLayout pnlMainScreenLayout = new javax.swing.GroupLayout(pnlMainScreen);
        pnlMainScreen.setLayout(pnlMainScreenLayout);
        pnlMainScreenLayout.setHorizontalGroup(
            pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabPaneMain)
                    .addComponent(lblMainBar, javax.swing.GroupLayout.PREFERRED_SIZE, 928, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        pnlMainScreenLayout.setVerticalGroup(
            pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                .addComponent(lblMainBar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabPaneMain, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlLoginScreen.setBackground(new java.awt.Color(213, 194, 177));

        lblLoginPageSideScreenIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tasktrack/resources/loginPageSideScreenIcon.png"))); // NOI18N
        lblLoginPageSideScreenIcon.setText("jLabel1");

        lblTaskTrack.setBackground(new java.awt.Color(213, 194, 177));
        lblTaskTrack.setFont(new java.awt.Font("Edwardian Script ITC", 0, 48)); // NOI18N
        lblTaskTrack.setText("Task Track");

        lblWelcomeTo.setBackground(new java.awt.Color(213, 194, 177));
        lblWelcomeTo.setFont(new java.awt.Font("Edwardian Script ITC", 0, 36)); // NOI18N
        lblWelcomeTo.setText("Welcome to");

        pnlLoginWithFacebook.setBackground(new java.awt.Color(184, 134, 125));
        pnlLoginWithFacebook.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlLoginWithFacebook.setPreferredSize(new java.awt.Dimension(229, 28));

        lblLoginWithFacebook.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        lblLoginWithFacebook.setForeground(new java.awt.Color(255, 255, 255));
        lblLoginWithFacebook.setText("Login with facebook");

        lblFacebookIcon.setPreferredSize(new java.awt.Dimension(16, 16));

        javax.swing.GroupLayout pnlLoginWithFacebookLayout = new javax.swing.GroupLayout(pnlLoginWithFacebook);
        pnlLoginWithFacebook.setLayout(pnlLoginWithFacebookLayout);
        pnlLoginWithFacebookLayout.setHorizontalGroup(
            pnlLoginWithFacebookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginWithFacebookLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFacebookIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblLoginWithFacebook)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLoginWithFacebookLayout.setVerticalGroup(
            pnlLoginWithFacebookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginWithFacebookLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFacebookIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlLoginWithFacebookLayout.createSequentialGroup()
                .addComponent(lblLoginWithFacebook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlLoginWithGoogle.setBackground(new java.awt.Color(184, 134, 125));
        pnlLoginWithGoogle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlLoginWithGoogle.setPreferredSize(new java.awt.Dimension(229, 28));

        lblLoginWithGoogle.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        lblLoginWithGoogle.setForeground(new java.awt.Color(255, 255, 255));
        lblLoginWithGoogle.setText("Login with google");

        javax.swing.GroupLayout pnlLoginWithGoogleLayout = new javax.swing.GroupLayout(pnlLoginWithGoogle);
        pnlLoginWithGoogle.setLayout(pnlLoginWithGoogleLayout);
        pnlLoginWithGoogleLayout.setHorizontalGroup(
            pnlLoginWithGoogleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginWithGoogleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGoogleIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginWithGoogleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLoginWithGoogle, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        pnlLoginWithGoogleLayout.setVerticalGroup(
            pnlLoginWithGoogleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginWithGoogleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblGoogleIcon)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginWithGoogleLayout.createSequentialGroup()
                .addComponent(lblLoginWithGoogle)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        lblOrLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblOrLabel.setText("-------------------------------Or---------------------------");

        txtFieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldUsernameActionPerformed(evt);
            }
        });

        lblUsernameIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tasktrack/resources/mainBar.png"))); // NOI18N
        lblUsernameIcon.setText("jLabel1");

        lblUsernameTitle.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        lblUsernameTitle.setText("Username");

        lblPasswordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tasktrack/resources/mainBar.png"))); // NOI18N
        lblPasswordIcon.setText("jLabel1");

        txtFieldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldPasswordActionPerformed(evt);
            }
        });

        lblPasswordTitle.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        lblPasswordTitle.setText("Password");

        lblForgotPassword.setFont(new java.awt.Font("Arial", 1, 8)); // NOI18N
        lblForgotPassword.setForeground(new java.awt.Color(130, 83, 78));
        lblForgotPassword.setLabelFor(txtFieldPassword);
        lblForgotPassword.setText("Forgot Password?");
        lblForgotPassword.setToolTipText("");

        btnLogin.setBackground(new java.awt.Color(184, 134, 125));
        btnLogin.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.setBorder(null);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblLoginError.setText(".");

        javax.swing.GroupLayout pnlLoginScreenLayout = new javax.swing.GroupLayout(pnlLoginScreen);
        pnlLoginScreen.setLayout(pnlLoginScreenLayout);
        pnlLoginScreenLayout.setHorizontalGroup(
            pnlLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLoginPageSideScreenIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginScreenLayout.createSequentialGroup()
                        .addGroup(pnlLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlLoginScreenLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(pnlLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblPasswordTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblOrLabel)
                                    .addGroup(pnlLoginScreenLayout.createSequentialGroup()
                                        .addComponent(lblUsernameIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(txtFieldUsername))
                                    .addComponent(lblUsernameTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlLoginScreenLayout.createSequentialGroup()
                                        .addComponent(lblPasswordIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(txtFieldPassword))
                                    .addComponent(pnlLoginWithGoogle, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                                    .addComponent(pnlLoginWithFacebook, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginScreenLayout.createSequentialGroup()
                                        .addComponent(lblTaskTrack, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlLoginScreenLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblForgotPassword)))
                        .addGap(1893, 1893, 1893))
                    .addGroup(pnlLoginScreenLayout.createSequentialGroup()
                        .addGroup(pnlLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlLoginScreenLayout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlLoginScreenLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(lblLoginError, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(pnlLoginScreenLayout.createSequentialGroup()
                .addGap(418, 418, 418)
                .addComponent(lblWelcomeTo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLoginScreenLayout.setVerticalGroup(
            pnlLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginScreenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblWelcomeTo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTaskTrack, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(pnlLoginWithFacebook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlLoginWithGoogle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblOrLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUsernameTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsernameIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPasswordTitle)
                .addGap(5, 5, 5)
                .addGroup(pnlLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPasswordIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblForgotPassword)
                .addGap(11, 11, 11)
                .addComponent(lblLoginError)
                .addGap(10, 10, 10)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginScreenLayout.createSequentialGroup()
                .addComponent(lblLoginPageSideScreenIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlTaskForm.setBackground(new java.awt.Color(221, 194, 173));
        pnlTaskForm.setMaximumSize(new java.awt.Dimension(1000, 1000));

        pnlTaskDataFormTitle.setBackground(new java.awt.Color(255, 255, 255));

        lblTaskDataFormTitle.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        lblTaskDataFormTitle.setForeground(new java.awt.Color(184, 134, 125));
        lblTaskDataFormTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTaskDataFormTitle.setText("Task Data Form");

        javax.swing.GroupLayout pnlTaskDataFormTitleLayout = new javax.swing.GroupLayout(pnlTaskDataFormTitle);
        pnlTaskDataFormTitle.setLayout(pnlTaskDataFormTitleLayout);
        pnlTaskDataFormTitleLayout.setHorizontalGroup(
            pnlTaskDataFormTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTaskDataFormTitleLayout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(lblTaskDataFormTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTaskDataFormTitleLayout.setVerticalGroup(
            pnlTaskDataFormTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTaskDataFormTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTaskDataFormTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtFieldAssignedDate.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Assigned Date", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        txtFieldAssignedDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldAssignedDateActionPerformed(evt);
            }
        });

        txtFieldTaskId.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Task ID", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        txtFieldTaskId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldTaskIdActionPerformed(evt);
            }
        });

        txtFieldProgress.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Progress", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        txtFieldProgress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldProgressActionPerformed(evt);
            }
        });

        txtFieldTaskTitle.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Task Title", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        txtFieldTaskTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldTaskTitleActionPerformed(evt);
            }
        });

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Completed", "In progress", "Missed", " " }));
        cbStatus.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Status", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.ABOVE_TOP));
        cbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbStatusActionPerformed(evt);
            }
        });

        txtFieldDueDate.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Due Date", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        txtFieldDueDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldDueDateActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(184, 134, 125));
        btnAdd.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        txtFieldAssignedTo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Assigned To", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        txtFieldAssignedTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldAssignedToActionPerformed(evt);
            }
        });

        txtFieldAssignedBy.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Assigned By", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        txtFieldAssignedBy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldAssignedByActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(184, 134, 125));
        btnDelete.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(184, 134, 125));
        btnUpdate.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTaskFormLayout = new javax.swing.GroupLayout(pnlTaskForm);
        pnlTaskForm.setLayout(pnlTaskFormLayout);
        pnlTaskFormLayout.setHorizontalGroup(
            pnlTaskFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTaskFormLayout.createSequentialGroup()
                .addGroup(pnlTaskFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTaskFormLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(pnlTaskFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlTaskFormLayout.createSequentialGroup()
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlTaskFormLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(pnlTaskFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFieldAssignedBy, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblErrorMsgAssignedBy, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(68, 68, 68)
                                .addGroup(pnlTaskFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblErrorMsgAssignedTo, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFieldAssignedTo, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pnlTaskFormLayout.createSequentialGroup()
                        .addComponent(lblErrorMsgTaskId, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblErrorMsgTaskTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(pnlTaskFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTaskFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTaskFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pnlTaskDataFormTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlTaskFormLayout.createSequentialGroup()
                            .addComponent(txtFieldAssignedDate, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, Short.MAX_VALUE)
                            .addComponent(txtFieldDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(pnlTaskFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtFieldProgress)
                                .addGroup(pnlTaskFormLayout.createSequentialGroup()
                                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlTaskFormLayout.createSequentialGroup()
                            .addComponent(txtFieldTaskId, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtFieldTaskTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(9, 9, 9)))
                    .addGroup(pnlTaskFormLayout.createSequentialGroup()
                        .addComponent(lblErrorMsgAssignedDate, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblErrorMsgDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblErrorMsgProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlTaskFormLayout.setVerticalGroup(
            pnlTaskFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTaskFormLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pnlTaskDataFormTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(pnlTaskFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldTaskId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldTaskTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTaskFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblErrorMsgTaskId, javax.swing.GroupLayout.DEFAULT_SIZE, 13, Short.MAX_VALUE)
                    .addComponent(lblErrorMsgTaskTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(pnlTaskFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlTaskFormLayout.createSequentialGroup()
                        .addGroup(pnlTaskFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFieldAssignedDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFieldDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFieldProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(pnlTaskFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblErrorMsgDueDate, javax.swing.GroupLayout.DEFAULT_SIZE, 13, Short.MAX_VALUE)
                            .addComponent(lblErrorMsgAssignedDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblErrorMsgProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pnlTaskFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldAssignedBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldAssignedTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(pnlTaskFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblErrorMsgAssignedBy, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                    .addComponent(lblErrorMsgAssignedTo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(pnlTaskFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdate)
                    .addGroup(pnlTaskFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAdd)
                        .addComponent(btnDelete))))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlLoadingPage.setBackground(new java.awt.Color(213, 194, 177));

        lblLoadingPageLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tasktrack/resources/logo.png"))); // NOI18N
        lblLoadingPageLogo.setText("jLabel1");

        pgBarLoadingScreen.setStringPainted(true);
        pgBarLoadingScreen.setBackground(new java.awt.Color(255, 255, 255));
        pgBarLoadingScreen.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        pgBarLoadingScreen.setForeground(new java.awt.Color(255, 255, 255));
        pgBarLoadingScreen.setToolTipText("");
        pgBarLoadingScreen.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(184, 134, 125), 5, true));
        pgBarLoadingScreen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblLoading.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblLoading.setForeground(new java.awt.Color(255, 255, 255));
        lblLoading.setText("Loading...........");

        javax.swing.GroupLayout pnlLoadingPageLayout = new javax.swing.GroupLayout(pnlLoadingPage);
        pnlLoadingPage.setLayout(pnlLoadingPageLayout);
        pnlLoadingPageLayout.setHorizontalGroup(
            pnlLoadingPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoadingPageLayout.createSequentialGroup()
                .addGroup(pnlLoadingPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoadingPageLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(pgBarLoadingScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLoadingPageLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(lblLoadingPageLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLoadingPageLayout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(lblLoading)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        pnlLoadingPageLayout.setVerticalGroup(
            pnlLoadingPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoadingPageLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(lblLoadingPageLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(pgBarLoadingScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoading)
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlLoadingPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlLoadingPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldUsernameActionPerformed

    private void txtFieldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldPasswordActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        // Get the username and password input
        String username = txtFieldUsername.getText();
        String password = new String(txtFieldPassword.getText());

        // Check if username or password is empty
        if (username.isEmpty() || password.isEmpty()) {
            lblLoginError.setText("Please enter your username and password.");
        } // Check if username and password are incorrect
        else if (!username.equals("admin") || !password.equals("admin")) {
            lblLoginError.setText("Username and password mismatch.");
        } // If credentials are correct, proceed to load the main screen
        else {
            lblLoginError.setText(""); // Clear any previous error messages
            loadScreen("MainScreen"); // Load the main screen
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtFieldAssignedDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldAssignedDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldAssignedDateActionPerformed

    private void txtFieldTaskIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldTaskIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldTaskIdActionPerformed

    private void txtFieldProgressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldProgressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldProgressActionPerformed

    private void txtFieldTaskTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldTaskTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldTaskTitleActionPerformed

    private void cbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStatusActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbStatusActionPerformed

    private void txtFieldDueDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldDueDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldDueDateActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:

        boolean isValid = true;

        // Validate TASK ID
        isValid &= validateField(
                txtFieldTaskId, "Task ID", lblErrorMsgTaskId, "Must be a 5-digit number.",
                errorColor, correctColor, ValidationUtil.isValidTaskId(txtFieldTaskId.getText())
        );

        // Validate task title
        isValid &= validateField(
                txtFieldTaskTitle, "Task Title", lblErrorMsgTaskTitle, "Must contain only alphabets.",
                errorColor, correctColor, ValidationUtil.isValidString(txtFieldTaskTitle.getText())
        );

        // Validate assigned by
        isValid &= validateField(
                txtFieldAssignedBy, "Assigned By", lblErrorMsgAssignedBy, "Must contain only alphabets.",
                errorColor, correctColor, ValidationUtil.isValidString(txtFieldAssignedBy.getText())
        );

        // Validate assigned to
        isValid &= validateField(
                txtFieldAssignedTo, "Assigned To", lblErrorMsgAssignedTo, "Must contain only alphabets.",
                errorColor, correctColor, ValidationUtil.isValidString(txtFieldAssignedTo.getText())
        );

        // Validate Assigned Date
        isValid &= validateField(
                txtFieldAssignedDate, "Assigned Date", lblErrorMsgAssignedDate, "Must be in YYYY-MM-DD format.",
                errorColor, correctColor, ValidationUtil.isValidDate(txtFieldAssignedDate.getText())
        );

        // Validate Due Date
        isValid &= validateField(
                txtFieldDueDate, "Due Date", lblErrorMsgDueDate, "Must be in YYYY-MM-DD format.",
                errorColor, correctColor, ValidationUtil.isValidDate(txtFieldDueDate.getText())
        );

        // Validate Due Date
        isValid &= validateField(
                txtFieldProgress, "Progress", lblErrorMsgProgress, "Must be 2 digit and end with %.",
                errorColor, correctColor, ValidationUtil.isValidProgress(txtFieldProgress.getText())
        );

        if (isValid) {
            // Create a StudentModel instance
            TaskModel newTask = new TaskModel(
                    Integer.parseInt(txtFieldTaskId.getText().trim()),
                    txtFieldTaskTitle.getText().trim(),
                    txtFieldAssignedBy.getText().trim(),
                    txtFieldAssignedTo.getText().trim(),
                    txtFieldAssignedDate.getText().trim(),
                    txtFieldDueDate.getText().trim(),
                    txtFieldProgress.getText().trim(),
                    (String) cbStatus.getSelectedItem());

            // Check for duplicate Task ID
            if (checkDuplicateTask(newTask)) {
                txtFieldTaskTitle.setBorder(createTitledBorder(errorColor, "Task ID"));
                showDialogBox("Task ID already exists.", "Duplicate Entry", JOptionPane.WARNING_MESSAGE);
            } else {
                // Add the student if no duplicate is found
                taskList.add(newTask);
                clearStudentForm();
                loadListToTable(taskList);
                txtFieldTaskId.setBorder(createTitledBorder(correctColor, "Task ID"));
                showDialogBox("Student added successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                loadScreen("MainScreen");
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void loadListToTable(List<TaskModel> taskList) {
        DefaultTableModel model = (DefaultTableModel) tblTasks.getModel();

        // Clear existing rows if needed
        model.setRowCount(0);

        // Populate the table with student data
        taskList.forEach(task -> model.addRow(new Object[]{
            task.getTaskId(),
            task.getTaskTitle(),
            task.getAssignedDate(),
            task.getDueDate(),
            task.getStatus(),
            task.getProgress(),
            task.getAssignedTo(),
            task.getAssignedTo()
        }));
    }

    private boolean validateField(JTextField textField, String fieldName, JLabel errorLbl, String errorMsg, Color errorColor, Color successColor, boolean isValidFormat) {
        if (ValidationUtil.isNullOrEmpty(textField.getText())) {
            textField.setBorder(createTitledBorder(errorColor, fieldName));
            errorLbl.setText("Field cannot be empty!");
            errorLbl.setVisible(true);
            return false;
        } else if (!isValidFormat) {
            textField.setBorder(createTitledBorder(errorColor, fieldName));
            errorLbl.setText(errorMsg);
            errorLbl.setVisible(true);
            return false;
        } else {
            textField.setBorder(createTitledBorder(successColor, fieldName));
            errorLbl.setVisible(false);
            return true;
        }
    }

    private javax.swing.border.TitledBorder createTitledBorder(Color color, String title) {
        return javax.swing.BorderFactory.createTitledBorder(
                javax.swing.BorderFactory.createLineBorder(color, 2),
                title,
                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                javax.swing.border.TitledBorder.DEFAULT_POSITION,
                new java.awt.Font("Segoe UI", 1, 12),
                color
        );
    }

    private void showDialogBox(String message, String title, int messageType) {
        JOptionPane.showMessageDialog(this, message, title, messageType);
    }

    private void clearStudentForm() {
        txtFieldTaskId.setText("");
        txtFieldTaskTitle.setText("");
        txtFieldProgress.setText("");
        txtFieldAssignedDate.setText("");
        txtFieldDueDate.setText("");
        txtFieldAssignedBy.setText("");
        txtFieldAssignedTo.setText("");
    }

    private boolean checkDuplicateTask(TaskModel task) {
        return taskList.stream()
                .anyMatch(existingStudent
                        -> existingStudent.getTaskId() == task.getTaskId());
    }


    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnGetStartedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetStartedActionPerformed
        // TODO add your handling code here:
        tabPaneMain.setSelectedIndex(1);
    }//GEN-LAST:event_btnGetStartedActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void txtFieldAssignedToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldAssignedToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldAssignedToActionPerformed

    private void txtFieldAssignedByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldAssignedByActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldAssignedByActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        boolean isValid = true;

        // Validate TASK ID
        isValid &= validateField(
                txtFieldTaskId, "Task ID", lblErrorMsgTaskId, "Must be a 5-digit number.",
                errorColor, correctColor, ValidationUtil.isValidTaskId(txtFieldTaskId.getText())
        );

        // Validate task title
        isValid &= validateField(
                txtFieldTaskTitle, "Task Title", lblErrorMsgTaskTitle, "Must contain only alphabets.",
                errorColor, correctColor, ValidationUtil.isValidString(txtFieldTaskTitle.getText())
        );

        // Validate assigned by
        isValid &= validateField(
                txtFieldAssignedBy, "Assigned By", lblErrorMsgAssignedBy, "Must contain only alphabets.",
                errorColor, correctColor, ValidationUtil.isValidString(txtFieldAssignedBy.getText())
        );

        // Validate assigned to
        isValid &= validateField(
                txtFieldAssignedTo, "Assigned To", lblErrorMsgAssignedTo, "Must contain only alphabets.",
                errorColor, correctColor, ValidationUtil.isValidString(txtFieldAssignedTo.getText())
        );

        // Validate Assigned Date
        isValid &= validateField(
                txtFieldAssignedDate, "Assigned Date", lblErrorMsgAssignedDate, "Must be in YYYY-MM-DD format.",
                errorColor, correctColor, ValidationUtil.isValidDate(txtFieldAssignedDate.getText())
        );

        // Validate Due Date
        isValid &= validateField(
                txtFieldDueDate, "Due Date", lblErrorMsgDueDate, "Must be in YYYY-MM-DD format.",
                errorColor, correctColor, ValidationUtil.isValidDate(txtFieldDueDate.getText())
        );

        // Validate Due Date
        isValid &= validateField(
                txtFieldProgress, "Progress", lblErrorMsgProgress, "Must be 2 digit and end with %.",
                errorColor, correctColor, ValidationUtil.isValidProgress(txtFieldProgress.getText())
        );
        if (isValid) {

            int taskId = Integer.parseInt(txtFieldTaskId.getText().trim());

            TaskModel taskToDelete = findTaskById(taskId);

            if (taskToDelete == null) {
                showDialogBox("Task ID not found.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            } else {
                taskList.remove(taskToDelete);
            }

            // Add the student if no duplicate is found
            clearStudentForm();
            loadListToTable(taskList);
            txtFieldTaskId.setBorder(createTitledBorder(correctColor, "Task ID"));
            showDialogBox("Task deleted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
            loadScreen("MainScreen");

        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        boolean isValid = true;

        // Validate TASK ID
        isValid &= validateField(
                txtFieldTaskId, "Task ID", lblErrorMsgTaskId, "Must be a 5-digit number.",
                errorColor, correctColor, ValidationUtil.isValidTaskId(txtFieldTaskId.getText())
        );

        // Validate task title
        isValid &= validateField(
                txtFieldTaskTitle, "Task Title", lblErrorMsgTaskTitle, "Must contain only alphabets.",
                errorColor, correctColor, ValidationUtil.isValidString(txtFieldTaskTitle.getText())
        );

        // Validate assigned by
        isValid &= validateField(
                txtFieldAssignedBy, "Assigned By", lblErrorMsgAssignedBy, "Must contain only alphabets.",
                errorColor, correctColor, ValidationUtil.isValidString(txtFieldAssignedBy.getText())
        );

        // Validate assigned to
        isValid &= validateField(
                txtFieldAssignedTo, "Assigned To", lblErrorMsgAssignedTo, "Must contain only alphabets.",
                errorColor, correctColor, ValidationUtil.isValidString(txtFieldAssignedTo.getText())
        );

        // Validate Assigned Date
        isValid &= validateField(
                txtFieldAssignedDate, "Assigned Date", lblErrorMsgAssignedDate, "Must be in YYYY-MM-DD format.",
                errorColor, correctColor, ValidationUtil.isValidDate(txtFieldAssignedDate.getText())
        );

        // Validate Due Date
        isValid &= validateField(
                txtFieldDueDate, "Due Date", lblErrorMsgDueDate, "Must be in YYYY-MM-DD format.",
                errorColor, correctColor, ValidationUtil.isValidDate(txtFieldDueDate.getText())
        );

        // Validate Due Date
        isValid &= validateField(
                txtFieldProgress, "Progress", lblErrorMsgProgress, "Must be 2 digit and end with %.",
                errorColor, correctColor, ValidationUtil.isValidProgress(txtFieldProgress.getText())
        );
        if (isValid) {

            int taskId = Integer.parseInt(txtFieldTaskId.getText().trim());

            TaskModel taskToUpdate = findTaskById(taskId);

            if (taskToUpdate == null) {
                showDialogBox("Task ID not found.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            } else {
                taskToUpdate.setTaskTitle(txtFieldTaskTitle.getText().trim());
                taskToUpdate.setAssignedBy(txtFieldAssignedBy.getText().trim());
                taskToUpdate.setAssignedTo(txtFieldAssignedTo.getText().trim());
                taskToUpdate.setAssignedDate(txtFieldAssignedDate.getText().trim());
                taskToUpdate.setDueDate(txtFieldDueDate.getText().trim());
                taskToUpdate.setProgress(txtFieldProgress.getText().trim());
                taskToUpdate.setStatus((String) cbStatus.getSelectedItem());
            }

            // Add the student if no duplicate is found
            clearStudentForm();
            loadListToTable(taskList);
            txtFieldTaskId.setBorder(createTitledBorder(correctColor, "Task ID"));
            showDialogBox("Task updated successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
            loadScreen("MainScreen");

        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private TaskModel findTaskById(int taskId) {
        for (TaskModel task : taskList) {
            if (task.getTaskId() == taskId) {
                return task;
            }
        }
        return null;
    }
    private void btnTaskDataFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaskDataFormActionPerformed
        // TODO add your handling code here:
        loadScreen("TaskScreen");

    }//GEN-LAST:event_btnTaskDataFormActionPerformed

    private void spTblTasksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spTblTasksMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_spTblTasksMouseClicked

    private void tblTasksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTasksMouseClicked

    }//GEN-LAST:event_tblTasksMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaskTrack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaskTrack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaskTrack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaskTrack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaskTrack().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnGetStarted;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnTaskDataForm;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblErrorMsgAssignedBy;
    private javax.swing.JLabel lblErrorMsgAssignedDate;
    private javax.swing.JLabel lblErrorMsgAssignedTo;
    private javax.swing.JLabel lblErrorMsgDueDate;
    private javax.swing.JLabel lblErrorMsgProgress;
    private javax.swing.JLabel lblErrorMsgTaskId;
    private javax.swing.JLabel lblErrorMsgTaskTitle;
    private javax.swing.JLabel lblFacebookIcon;
    private javax.swing.JLabel lblForgotPassword;
    private javax.swing.JLabel lblGoogleIcon;
    private javax.swing.JLabel lblLoading;
    private javax.swing.JLabel lblLoadingPageLogo;
    private javax.swing.JLabel lblLoginError;
    private javax.swing.JLabel lblLoginPageSideScreenIcon;
    private javax.swing.JLabel lblLoginWithFacebook;
    private javax.swing.JLabel lblLoginWithGoogle;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMainBar;
    private javax.swing.JLabel lblOrLabel;
    private javax.swing.JLabel lblPasswordIcon;
    private javax.swing.JLabel lblPasswordTitle;
    private javax.swing.JLabel lblTaskDataFormTitle;
    private javax.swing.JLabel lblTaskListTitle;
    private javax.swing.JLabel lblTaskTrack;
    private javax.swing.JLabel lblUsernameIcon;
    private javax.swing.JLabel lblUsernameTitle;
    private javax.swing.JLabel lblWelcomeTo;
    private javax.swing.JProgressBar pgBarLoadingScreen;
    private javax.swing.JPanel pnlAboutUs;
    private javax.swing.JPanel pnlAboutUsTitle;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlLoadingPage;
    private javax.swing.JPanel pnlLoginScreen;
    private javax.swing.JPanel pnlLoginWithFacebook;
    private javax.swing.JPanel pnlLoginWithGoogle;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JPanel pnlMainScreen;
    private javax.swing.JPanel pnlTaskDataFormTitle;
    private javax.swing.JPanel pnlTaskForm;
    private javax.swing.JPanel pnlTaskListTitle;
    private javax.swing.JPanel pnlTasks;
    private javax.swing.JScrollPane spTblTasks;
    private javax.swing.JTabbedPane tabPaneMain;
    private javax.swing.JTable tblTasks;
    private javax.swing.JTextField txtFieldAssignedBy;
    private javax.swing.JTextField txtFieldAssignedDate;
    private javax.swing.JTextField txtFieldAssignedTo;
    private javax.swing.JTextField txtFieldDueDate;
    private javax.swing.JTextField txtFieldPassword;
    private javax.swing.JTextField txtFieldProgress;
    private javax.swing.JTextField txtFieldTaskId;
    private javax.swing.JTextField txtFieldTaskTitle;
    private javax.swing.JTextField txtFieldUsername;
    // End of variables declaration//GEN-END:variables
}
